In [3]:
import meaningcloud
from time import sleep
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
meaningcloud_key = '6080c92cd8055f28dfc07b5619464baf'

def meaningcloud_analysis (text):  
    sleep (0.5)
    try:
        mc_topics =  meaningcloud.TopicsResponse(meaningcloud.TopicsRequest(meaningcloud_key, lang='en', txt=text).sendReq())
        mc_dict = mc_topics.getResults()
        results = mc_dict['concept_list']
        return results
        print (results)
    except:
        print("There was an error! "+ mc_topics.getStatusMsg())
        return None

In [5]:
with open ("sound_project_1.txt", "r") as file:
    data=file.readlines()

In [6]:
mc_output = meaningcloud_analysis(data)

In [7]:
topics = []
for i in mc_output:
    topics.append(i['form'])

In [13]:
freq = {} 
for items in topics: 
    freq[items] = topics.count(items)

In [22]:
freq

{'people': 1,
 'kind': 2,
 'job': 1,
 'home': 1,
 'city': 1,
 'friend': 1,
 'quality of life': 1,
 'plug': 2,
 'green card': 1,
 'computer science': 1,
 'place': 1,
 'credit score': 1,
 'coffee shop': 1,
 'New Yorker': 2,
 'side effect': 1,
 'emporium': 1,
 'medical care': 1,
 'sports field': 1,
 'degree Celsius': 1,
 'high-end': 1,
 'urban plan': 1,
 'urbanism': 1,
 'bourgeoisie': 1,
 'Native American': 1,
 'industrial revolution': 1,
 'middle class': 1,
 'data analysis': 1,
 'visa': 1,
 'family': 1,
 'train': 1,
 'tale': 1,
 'couple': 1,
 'school': 1,
 'person': 1,
 'bridge': 2,
 'American': 4,
 'decision': 1,
 'neighborhood': 1,
 'student': 1,
 'subway': 1,
 'Chinese': 3,
 'kid': 1,
 'store': 3,
 'country': 1,
 'citizenship': 1,
 'passport': 1,
 'occasion': 1,
 'teacher': 2,
 'underground': 1,
 'program': 1,
 'ton': 1,
 'horse': 1,
 'noise': 1,
 'floor': 1,
 'flat': 1,
 'music': 1,
 'environment': 2,
 'finance': 1,
 'project': 1,
 'culture': 1,
 'group': 1,
 'magazine': 1,
 'side': 2,
 'garbage': 1,
 'tourist': 1,
 'field': 2,
 'street': 1,
 'question': 1,
 'bond': 1,
 'honeymoon': 1,
 'plan': 1,
 'left': 1,
 'food': 1,
 'French': 2,
 'guy': 1,
 'glass': 2,
 'coffee': 1,
 'meaning': 1,
 'woman': 1,
 'organization': 1,
 'history': 1,
 'company': 1,
 'audience': 1,
 'ground': 1,
 'art': 1,
 'trade': 2,
 'special': 1,
 'software': 1,
 'world': 1,
 'buyer': 1,
 'product': 1,
 'boyfriend': 1,
 'aircraft': 1,
 'sister': 1,
 'beverage': 1,
 'uncle': 1,
 'high': 1,
 'hank': 1,
 'reporter': 1,
 'contract': 1,
 'root': 1,
 'designer': 2,
 'journalist': 1,
 'father': 1,
 'sex': 1,
 'lost': 1,
 'dinner': 2,
 'citizen': 1,
 'state': 1,
 'pregnant': 1,
 'emperor': 1,
 'winter': 1,
 'tunnel': 1,
 'Asian': 1,
 'space': 2,
 'brain': 1,
 'film': 1,
 'scholarship': 1,
 'connection': 2,
 'man': 1,
 'chance': 1,
 'cockroach': 1,
 'class': 1,
 'tissue': 1,
 'love': 2,
 'ear': 1,
 'spot': 1,
 'advertisement': 1,
 'mother': 1,
 'shoulder': 2,
 'court': 3,
 'stratum': 2,
 'car': 1,
 'stock': 1,
 'dog': 1,
 'chassis': 1,
 'immigrant': 1,
 'fire': 1,
 'methodology': 1,
 'container': 1,
 'framework': 1,
 'dance': 2,
 'red': 1,
 'strategy': 1,
 'lady': 1,
 'email': 1,
 'square': 2,
 'vision': 1,
 'battle': 1,
 'child': 1,
 'rent': 1,
 'baby': 1,
 'dream': 1,
 'balcony': 1,
 'solicitor': 1,
 'opponent': 1,
 'song': 1,
 'appearance': 1,
 'judge': 1,
 'policy': 2,
 'tennis': 2,
 'stress': 1,
 'construction': 1,
 'novice': 1,
 'cold': 2,
 'article': 2,
 'advent': 1,
 'telephone': 1,
 'attorney': 1,
 'head': 1,
 'fight': 1,
 'freedom': 1,
 'risk': 1,
 'nationalist': 1,
 'appointment': 1,
 'drum': 1,
 'defense': 2,
 'European': 1,
 'continent': 1,
 'start': 1,
 'noodle': 1,
 'client': 1,
 'partner': 1,
 'black': 1,
 'white': 1,
 'book': 1,
 'photograph': 1,
 'conclusion': 1,
 'nail': 1,
 'financial': 1,
 'theory': 1,
 'museum': 1,
 'garage': 1,
 'aggressive': 1,
 'leg': 2,
 'lax': 1,
 'pollution': 1,
 'gallery': 1,
 'center': 3,
 'event': 1,
 'donation': 1,
 'community': 1,
 'Internet': 1,
 'recording': 1,
 'writer': 1,
 'author': 1,
 'west': 1,
 'politics': 1,
 'energy': 1,
 'area': 1,
 'construcci√≥n': 1,
 'bagel': 1,
 'library': 1,
 'factory': 1,
 'speaker': 3,
 'gold': 2,
 'spreading': 1,
 'forest': 1,
 'avenue': 1,
 'garden': 1,
 'decal': 1,
 'cheese': 1,
 'farm': 2,
 'path': 1,
 'ancestor': 3,
 'statue': 1,
 'land': 1,
 'distance': 1,
 'bread': 1,
 'crisis': 1,
 'player': 1,
 'colleague': 1,
 'language': 1,
 'health': 1,
 'PlayStation': 1,
 'attachment': 1,
 'cut': 1,
 'chapter': 1,
 'mood': 1,
 'location': 2,
 'entrance': 1,
 'load': 1,
 'visitor': 1,
 'holiday': 1,
 'soccer': 1,
 'university': 1,
 'parliament': 1,
 'alien': 1,
 'garment': 1,
 'footwear': 1,
 'feature': 1,
 'report': 1,
 'cart': 1,
 'incident': 1,
 'ass': 1,
 'donkey': 1,
 'dollar': 1,
 'sandwich': 1,
 'cream': 1,
 'village': 1,
 'platform': 3,
 'acute': 1,
 'industry': 1,
 'husband': 1,
 'ballet': 1,
 'sea': 1,
 'documentary': 1,
 'universe': 1,
 'planet': 1,
 'interview': 1,
 'short': 1,
 'town': 2,
 'female': 1,
 'married': 1,
 'ideology': 1,
 'net': 1,
 'migration': 1,
 'Nazi': 1,
 'base': 1,
 'engineer': 1,
 'curriculum vitae': 1,
 'Summer': 1,
 'science': 1,
 'photographer': 1,
 'nationalism': 1,
 'intention': 1,
 'research': 1,
 'guest': 2,
 'conference': 1,
 'conflict': 2,
 'access': 1,
 'activity': 1,
 'lottery': 1,
 'engineering': 1,
 'master': 1,
 'ability': 1,
 'artist': 1,
 'authorization': 1,
 'room': 2,
 'breakfast': 2,
 'figure': 2,
 'favorite': 1,
 'compass': 1,
 'tavern': 1,
 'ale': 1}

In [20]:
topics_list=freq.keys()
count_list=freq.values()

In [24]:
df_topics=pd.DataFrame()

In [25]:
df_topics.head()

Empty DataFrame
Columns: []
Index: []

In [27]:
df_topics.insert(loc=0, column = 'topic', value = topics_list)

In [28]:
df_topics.insert(loc=0, column = 'freq', value = count_list)

In [29]:
df_topics.head()

   freq   topic
0     1  people
1     2    kind
2     1     job
3     1    home
4     1    city

In [38]:
df_topics.sort_values('freq',ascending=False, inplace=True)

In [39]:
df_topics.head(20)

     freq        topic
35      4     American
214     3      speaker
224     3     ancestor
130     3        court
260     3     platform
198     3       center
40      3      Chinese
42      3        store
56      2  environment
62      2         side
165     2      article
106     2       dinner
124     2         love
47      2      teacher
131     2      stratum
129     2     shoulder
114     2        space
271     2         town
141     2        dance
65      2        field